<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

# Trabajo Final - Máster en Big Data - Fernández, García y Payovich

## Modelos de Base: Random Forest, Bagging, Boosting y Stacking

### Importación de Librerías

In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # División del dataset
import matplotlib.pyplot as plt # Plotear
from sklearn.linear_model import LinearRegression # Modelo de ML
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, classification_report # Métricas
pd.options.display.max_columns= None
import warnings

In [2]:
warnings.filterwarnings('ignore')

### Importación y Transformación de las Bases

In [3]:
df = pd.read_csv('base_final_EDA.csv', delimiter= ',')

In [4]:
dfr = df.astype(int)

In [5]:
x = df.drop(['detractor'], axis=1)

In [6]:
x_r = dfr.drop(['detractor'], axis=1)

In [7]:
y = df['detractor']

In [8]:
y_r = dfr['detractor']

### Sampleo y Escalado de Datos:

In [10]:
#OverSampling:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
x_sm, y_sm = sm.fit_resample(x, y)

In [11]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state = 42)
x_us, y_us = rus.fit_resample(x, y)

In [12]:
x_train_rf, x_test, y_train, y_test = train_test_split(x, y,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [13]:
x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(x_r, y_r,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

### Random Forest:

In [14]:
x_train_rf, x_test_rf, y_train_rf, y_test_rf = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_rf = sc.fit_transform(x_train_rf)
#Escalo Datos de Testeo:
x_test_rf = sc.fit_transform(x_test_rf)

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf.fit(x_train_rf, y_train_rf)
y_pred_rf = rf.predict(x_test_rf).round()

In [17]:
accuracy_rf = accuracy_score(y_test_rf, y_pred_rf)
print('Accuracy del modelo Random Forest: %.3f' % accuracy_rf)

Accuracy del modelo Random Forest: 0.829


In [18]:
precision_rf = precision_score(y_test_rf, y_pred_rf)
print('Precision del modelo Random Forest: %.3f' % precision_rf)

Precision del modelo Random Forest: 0.000


In [19]:
recall_rf = recall_score(y_test_rf, y_pred_rf)
print('Recall del Modelo Random Forest: %.3f' % recall_rf)

Recall del Modelo Random Forest: 0.000


In [20]:
matriz_rf = confusion_matrix(y_test_rf, y_pred_rf)
print('Matriz de Confusión:')
print(matriz_rf)

Matriz de Confusión:
[[1935    0]
 [ 398    0]]


In [21]:
print(classification_report(y_test_rf, y_pred_rf))

              precision    recall  f1-score   support

       False       0.83      1.00      0.91      1935
        True       0.00      0.00      0.00       398

    accuracy                           0.83      2333
   macro avg       0.41      0.50      0.45      2333
weighted avg       0.69      0.83      0.75      2333



### Random Forest con Oversampling:

In [22]:
x_train_sm, x_test_sm, y_train_sm, y_test_sm = train_test_split(x_sm, y_sm,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm = sc.fit_transform(x_train_sm)
#Escalo Datos de Testeo:
x_test_sm = sc.fit_transform(x_test_sm)

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf_sm = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_sm.fit(x_train_sm, y_train_sm)
y_pred_sm = rf_sm.predict(x_test_sm).round()

In [25]:
accuracy_rf_sm = accuracy_score(y_test_sm, y_pred_sm)
print('Accuracy del Random Forest con Oversampling: %.3f' % accuracy_rf_sm)

Accuracy del Random Forest con Oversampling: 0.696


In [26]:
precision_sm = precision_score(y_test_sm, y_pred_sm)
print('Precision del modelo Random Forest con Oversampling: %.3f' % precision_sm)

Precision del modelo Random Forest con Oversampling: 0.634


In [27]:
recall_sm = recall_score(y_test_sm, y_pred_sm)
print('Recall del Modelo Random Forest con Oversampling: %.3f' % recall_sm)

Recall del Modelo Random Forest con Oversampling: 0.935


In [28]:
matriz_sm = confusion_matrix(y_test_sm, y_pred_sm)
print('Matriz de Confusión:')
print(matriz_sm)

Matriz de Confusión:
[[ 885 1067]
 [ 128 1845]]


In [29]:
print(classification_report(y_test_sm, y_pred_sm))

              precision    recall  f1-score   support

       False       0.87      0.45      0.60      1952
        True       0.63      0.94      0.76      1973

    accuracy                           0.70      3925
   macro avg       0.75      0.69      0.68      3925
weighted avg       0.75      0.70      0.68      3925



### Random Forest con Undersampling

In [30]:
x_train_us, x_test_us, y_train_us, y_test_us = train_test_split(x_us, y_us,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_us = sc.fit_transform(x_train_us)
#Escalo Datos de Testeo:
x_test_us = sc.fit_transform(x_test_us)

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf_us = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_us.fit(x_train_us, y_train_us)
y_pred_us = rf_us.predict(x_test_us).round()

In [33]:
accuracy_rf_us = accuracy_score(y_test_us, y_pred_us)
print('Accuracy del Random Forest con Undersampling: %.3f' % accuracy_rf_us)

Accuracy del Random Forest con Undersampling: 0.589


In [34]:
precision_us = precision_score(y_test_us, y_pred_us)
print('Precision del modelo Random Forest con Undersampling %.3f' % precision_us)

Precision del modelo Random Forest con Undersampling 0.576


In [35]:
recall_us = recall_score(y_test_us, y_pred_us)
print('Recall del Modelo Random Forest con Undersampling: %.3f' % recall_us)

Recall del Modelo Random Forest con Undersampling: 0.560


In [36]:
matriz_us = confusion_matrix(y_test_us, y_pred_us)
print('Matriz de Confusión:')
print(matriz_us)

Matriz de Confusión:
[[236 147]
 [157 200]]


In [37]:
print(classification_report(y_test_us, y_pred_us))

              precision    recall  f1-score   support

       False       0.60      0.62      0.61       383
        True       0.58      0.56      0.57       357

    accuracy                           0.59       740
   macro avg       0.59      0.59      0.59       740
weighted avg       0.59      0.59      0.59       740



### Bagging

In [38]:
x_train_bg, x_test_bg, y_train_bg, y_test_bg = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_bg = sc.fit_transform(x_train_bg)
#Escalo Datos de Testeo:
x_test_bg = sc.fit_transform(x_test_bg)

In [40]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

bagging.fit(x_train_bg, y_train_bg)

BaggingClassifier(n_jobs=-1, random_state=55)

In [41]:
y_pred_bg = bagging.predict(x_test_bg)

In [42]:
accuracy_bg = accuracy_score(y_test_bg, y_pred_bg)
print('Accuracy del Modelo de Bagging: %.3f' % accuracy_bg)

Accuracy del Modelo de Bagging: 0.814


In [43]:
precision_bg = precision_score(y_test_bg, y_pred_bg)
print('Precision del Modelo de Bagging: %.3f' % precision_bg)

Precision del Modelo de Bagging: 0.235


In [44]:
recall_bg = recall_score(y_test_bg, y_pred_bg)
print('Recall del Modelo de Bagging: %.3f' % recall_bg)

Recall del Modelo de Bagging: 0.040


In [45]:
matriz_bg = confusion_matrix(y_test_bg, y_pred_bg)
print('Matriz de Confusión:')
print(matriz_bg)

Matriz de Confusión:
[[1883   52]
 [ 382   16]]


In [46]:
print(classification_report(y_test_bg, y_pred_bg))

              precision    recall  f1-score   support

       False       0.83      0.97      0.90      1935
        True       0.24      0.04      0.07       398

    accuracy                           0.81      2333
   macro avg       0.53      0.51      0.48      2333
weighted avg       0.73      0.81      0.76      2333



### Boosting

In [47]:
x_train_boo, x_test_boo, y_train_boo, y_test_boo = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_boo = sc.fit_transform(x_train_boo)
#Escalo Datos de Testeo:
x_test_boo = sc.fit_transform(x_test_boo)

In [49]:
import xgboost as xgb

boosting = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric='logloss'
)
boosting.fit(x_train_boo, y_train_boo)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=3, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, ...)

In [50]:
y_pred_boo = boosting.predict(x_test_boo)
accuracy_boo = accuracy_score(y_test_boo, y_pred_boo)
print('Accuracy del Modelo de Boosting: %.3f' % accuracy_boo)

Accuracy del Modelo de Boosting: 0.841


In [51]:
precision_boo = precision_score(y_test_boo, y_pred_boo)
print('Precision del Modelo de Boosting: %.3f' % precision_boo)

Precision del Modelo de Boosting: 0.000


In [52]:
recall_boo = recall_score(y_test_boo, y_pred_boo)
print('Recall del Modelo de Boosting: %.3f' % recall_boo)

Recall del Modelo de Boosting: 0.000


In [53]:
matriz_boo = confusion_matrix(y_test_boo, y_pred_boo)
print('Matriz de Confusión:')
print(matriz_boo)

Matriz de Confusión:
[[1962    0]
 [ 371    0]]


In [54]:
print(classification_report(y_test_boo, y_pred_boo))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91      1962
        True       0.00      0.00      0.00       371

    accuracy                           0.84      2333
   macro avg       0.42      0.50      0.46      2333
weighted avg       0.71      0.84      0.77      2333



### Stacking

In [55]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [56]:
x_train_st, x_test_st, y_train_st, y_test_st = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_st = sc.fit_transform(x_train_st)
#Escalo Datos de Testeo:
x_test_st = sc.fit_transform(x_test_st)

In [58]:
modelos_stacking = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stacking = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stacking.fit(x_train_st, y_train_st)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [59]:
y_pred_st = stacking.predict(x_test_st)
accuracy_st = accuracy_score(y_test_st, y_pred_st)
print(f'Accuracy del Modelo de Stacking: {accuracy_st:4f}')

Accuracy del Modelo de Stacking: 0.840977


In [60]:
precision_st = precision_score(y_test_st, y_pred_st)
print('Precision del Modelo de Stacking: %.3f' % precision_st)

Precision del Modelo de Stacking: 0.000


In [61]:
recall_st = recall_score(y_test_st, y_pred_st)
print('Recall del Modelo de Boosting: %.3f' % recall_st)

Recall del Modelo de Boosting: 0.000


In [62]:
matriz_st = confusion_matrix(y_test_st, y_pred_st)
print('Matriz de Confusión:')
print(matriz_st)

Matriz de Confusión:
[[1962    0]
 [ 371    0]]


In [63]:
print(classification_report(y_test_st, y_pred_st))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91      1962
        True       0.00      0.00      0.00       371

    accuracy                           0.84      2333
   macro avg       0.42      0.50      0.46      2333
weighted avg       0.71      0.84      0.77      2333



### Stacking con Oversampling

In [64]:
x_train_smst, x_test_smst, y_train_smst, y_test_smst = train_test_split(x_sm, y_sm,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_smst = sc.fit_transform(x_train_smst)
#Escalo Datos de Testeo:
x_test_smst = sc.fit_transform(x_test_smst)

In [66]:
modelos_stacking = [
   ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('xg', xgb.XGBClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stacking = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stacking.fit(x_train_smst, y_train_smst)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('xg',
                                XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=False,
                                              eval_metric=None, gamma=None,
                                              gpu_id=None, grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=None, max_bin=None,
            

In [67]:
y_pred_smst = stacking.predict(x_test_smst)
accuracy_smst = accuracy_score(y_test_smst, y_pred_smst)
print(f'Accuracy del Modelo de Stacking con Oversampling: {accuracy_smst:4f}')

Accuracy del Modelo de Stacking con Oversampling: 0.545478


In [68]:
precision_smst = precision_score(y_test_smst, y_pred_smst)
print('Precision del Modelo de Stacking con Oversampling: %.3f' % precision_smst)

Precision del Modelo de Stacking con Oversampling: 0.525


In [69]:
recall_smst = recall_score(y_test_smst, y_pred_smst)
print('Recall del Modelo de Stacking con Oversampling: %.3f' % recall_smst)

Recall del Modelo de Stacking con Oversampling: 0.990


In [70]:
matriz_smst = confusion_matrix(y_test_smst, y_pred_smst)
print('Matriz de Confusión:')
print(matriz_smst)

Matriz de Confusión:
[[ 188 1764]
 [  20 1953]]


In [71]:
print(classification_report(y_test_smst, y_pred_smst))

              precision    recall  f1-score   support

       False       0.90      0.10      0.17      1952
        True       0.53      0.99      0.69      1973

    accuracy                           0.55      3925
   macro avg       0.71      0.54      0.43      3925
weighted avg       0.71      0.55      0.43      3925

