<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

# Trabajo Final - Máster en Big Data - Fernández, García y Payovich

## Modelos de Base: Random Forest, Bagging, Boosting y Stacking

### Importación de Librerías

In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # División del dataset
import matplotlib.pyplot as plt # Plotear
from sklearn.linear_model import LinearRegression # Modelo de ML
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, classification_report # Métricas
pd.options.display.max_columns= None
import warnings

In [2]:
warnings.filterwarnings('ignore')

### Importación y Transformación de las Bases

In [3]:
df = pd.read_csv('base_final_EDA.csv', delimiter= ',')

In [4]:
dfr = df.astype(int)

In [5]:
x = df.drop(['detractor'], axis=1)

In [6]:
x_r = dfr.drop(['detractor'], axis=1)

In [7]:
y = df['detractor']

In [8]:
y_r = dfr['detractor']

### Sampleo y Escalado de Datos:

In [10]:
#OverSampling:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
x_sm, y_sm = sm.fit_resample(x, y)

In [11]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state = 42)
x_us, y_us = rus.fit_resample(x, y)

### Random Forest:

In [12]:
x_train_rf, x_test_rf, y_train_rf, y_test_rf = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_rf = sc.fit_transform(x_train_rf)
#Escalo Datos de Testeo:
x_test_rf = sc.fit_transform(x_test_rf)

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf.fit(x_train_rf, y_train_rf)
y_pred_rf = rf.predict(x_test_rf).round()

In [15]:
accuracy_rf = accuracy_score(y_test_rf, y_pred_rf)
print('Accuracy del modelo Random Forest: %.3f' % accuracy_rf)

Accuracy del modelo Random Forest: 0.829


In [16]:
precision_rf = precision_score(y_test_rf, y_pred_rf)
print('Precision del modelo Random Forest: %.3f' % precision_rf)

Precision del modelo Random Forest: 0.000


In [17]:
recall_rf = recall_score(y_test_rf, y_pred_rf)
print('Recall del Modelo Random Forest: %.3f' % recall_rf)

Recall del Modelo Random Forest: 0.000


In [18]:
matriz_rf = confusion_matrix(y_test_rf, y_pred_rf)
print('Matriz de Confusión:')
print(matriz_rf)

Matriz de Confusión:
[[1935    0]
 [ 398    0]]


In [19]:
print(classification_report(y_test_rf, y_pred_rf))

              precision    recall  f1-score   support

       False       0.83      1.00      0.91      1935
        True       0.00      0.00      0.00       398

    accuracy                           0.83      2333
   macro avg       0.41      0.50      0.45      2333
weighted avg       0.69      0.83      0.75      2333



### Random Forest con Oversampling:

In [20]:
x_train_sm, x_test_sm, y_train_sm, y_test_sm = train_test_split(x_sm, y_sm,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm = sc.fit_transform(x_train_sm)
#Escalo Datos de Testeo:
x_test_sm = sc.fit_transform(x_test_sm)

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf_sm = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_sm.fit(x_train_sm, y_train_sm)
y_pred_sm = rf_sm.predict(x_test_sm).round()

In [23]:
accuracy_rf_sm = accuracy_score(y_test_sm, y_pred_sm)
print('Accuracy del Random Forest con Oversampling: %.3f' % accuracy_rf_sm)

Accuracy del Random Forest con Oversampling: 0.696


In [24]:
precision_sm = precision_score(y_test_sm, y_pred_sm)
print('Precision del modelo Random Forest con Oversampling: %.3f' % precision_sm)

Precision del modelo Random Forest con Oversampling: 0.634


In [25]:
recall_sm = recall_score(y_test_sm, y_pred_sm)
print('Recall del Modelo Random Forest con Oversampling: %.3f' % recall_sm)

Recall del Modelo Random Forest con Oversampling: 0.935


In [26]:
matriz_sm = confusion_matrix(y_test_sm, y_pred_sm)
print('Matriz de Confusión:')
print(matriz_sm)

Matriz de Confusión:
[[ 885 1067]
 [ 128 1845]]


In [27]:
print(classification_report(y_test_sm, y_pred_sm))

              precision    recall  f1-score   support

       False       0.87      0.45      0.60      1952
        True       0.63      0.94      0.76      1973

    accuracy                           0.70      3925
   macro avg       0.75      0.69      0.68      3925
weighted avg       0.75      0.70      0.68      3925



### Random Forest con Undersampling

In [28]:
x_train_us, x_test_us, y_train_us, y_test_us = train_test_split(x_us, y_us,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_us = sc.fit_transform(x_train_us)
#Escalo Datos de Testeo:
x_test_us = sc.fit_transform(x_test_us)

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf_us = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_us.fit(x_train_us, y_train_us)
y_pred_us = rf_us.predict(x_test_us).round()

In [31]:
accuracy_rf_us = accuracy_score(y_test_us, y_pred_us)
print('Accuracy del Random Forest con Undersampling: %.3f' % accuracy_rf_us)

Accuracy del Random Forest con Undersampling: 0.589


In [32]:
precision_us = precision_score(y_test_us, y_pred_us)
print('Precision del modelo Random Forest con Undersampling %.3f' % precision_us)

Precision del modelo Random Forest con Undersampling 0.576


In [33]:
recall_us = recall_score(y_test_us, y_pred_us)
print('Recall del Modelo Random Forest con Undersampling: %.3f' % recall_us)

Recall del Modelo Random Forest con Undersampling: 0.560


In [34]:
matriz_us = confusion_matrix(y_test_us, y_pred_us)
print('Matriz de Confusión:')
print(matriz_us)

Matriz de Confusión:
[[236 147]
 [157 200]]


In [35]:
print(classification_report(y_test_us, y_pred_us))

              precision    recall  f1-score   support

       False       0.60      0.62      0.61       383
        True       0.58      0.56      0.57       357

    accuracy                           0.59       740
   macro avg       0.59      0.59      0.59       740
weighted avg       0.59      0.59      0.59       740



### Bagging

In [36]:
x_train_bg, x_test_bg, y_train_bg, y_test_bg = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_bg = sc.fit_transform(x_train_bg)
#Escalo Datos de Testeo:
x_test_bg = sc.fit_transform(x_test_bg)

In [38]:
x_train_sm_bg, x_test_sm_bg, y_train_sm_bg, y_test_sm_bg = train_test_split(x_sm, y_sm,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm_bg = sc.fit_transform(x_train_sm_bg)
#Escalo Datos de Testeo:
x_test_sm_bg = sc.fit_transform(x_test_sm_bg)

In [40]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

bagging.fit(x_train_bg, y_train_bg)

BaggingClassifier(n_jobs=-1, random_state=55)

In [41]:
bagging = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

bagging.fit(x_train_sm_bg, y_train_sm_bg)

BaggingClassifier(n_jobs=-1, random_state=55)

In [42]:
y_pred_bg = bagging.predict(x_test_bg)

In [43]:
y_pred_sm_bg = bagging.predict(x_test_sm_bg)

In [44]:
accuracy_bg = accuracy_score(y_test_bg, y_pred_bg)
print('Accuracy del Modelo de Bagging: %.3f' % accuracy_bg)

Accuracy del Modelo de Bagging: 0.439


In [45]:
accuracy_sm_bg = accuracy_score(y_test_sm_bg, y_pred_sm_bg)
print('Accuracy del Modelo de Bagging con Oversampling: %.3f' % accuracy_sm_bg)

Accuracy del Modelo de Bagging con Oversampling: 0.738


In [46]:
precision_bg = precision_score(y_test_bg, y_pred_bg)
print('Precision del Modelo de Bagging: %.3f' % precision_bg)

Precision del Modelo de Bagging: 0.208


In [47]:
precision_sm_bg = precision_score(y_test_sm_bg, y_pred_sm_bg)
print('Precision del Modelo de Bagging con Oversampling: %.3f' % precision_sm_bg)

Precision del Modelo de Bagging con Oversampling: 0.683


In [48]:
recall_bg = recall_score(y_test_bg, y_pred_bg)
print('Recall del Modelo de Bagging: %.3f' % recall_bg)

Recall del Modelo de Bagging: 0.814


In [49]:
recall_sm_bg = recall_score(y_test_sm_bg, y_pred_sm_bg)
print('Recall del Modelo de Bagging con Oversampling: %.3f' % recall_sm_bg)

Recall del Modelo de Bagging con Oversampling: 0.881


In [50]:
matriz_bg = confusion_matrix(y_test_bg, y_pred_bg)
print('Matriz de Confusión Bagging:')
print(matriz_bg)

Matriz de Confusión Bagging:
[[ 701 1234]
 [  74  324]]


In [51]:
matriz_sm_bg = confusion_matrix(y_test_sm_bg, y_pred_sm_bg)
print('Matriz de Confusión Bagging con Oversampling:')
print(matriz_sm_bg)

Matriz de Confusión Bagging con Oversampling:
[[1172  798]
 [ 232 1723]]


In [52]:
print(classification_report(y_test_bg, y_pred_bg))

              precision    recall  f1-score   support

       False       0.90      0.36      0.52      1935
        True       0.21      0.81      0.33       398

    accuracy                           0.44      2333
   macro avg       0.56      0.59      0.42      2333
weighted avg       0.79      0.44      0.49      2333



In [53]:
print(classification_report(y_test_sm_bg, y_pred_sm_bg))

              precision    recall  f1-score   support

       False       0.83      0.59      0.69      1970
        True       0.68      0.88      0.77      1955

    accuracy                           0.74      3925
   macro avg       0.76      0.74      0.73      3925
weighted avg       0.76      0.74      0.73      3925



### Boosting

In [54]:
x_train_boo, x_test_boo, y_train_boo, y_test_boo = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_boo = sc.fit_transform(x_train_boo)
#Escalo Datos de Testeo:
x_test_boo = sc.fit_transform(x_test_boo)

In [56]:
x_train_sm_boo, x_test_sm_boo, y_train_sm_boo, y_test_sm_boo = train_test_split(x_sm, y_sm,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm_boo = sc.fit_transform(x_train_sm_boo)
#Escalo Datos de Testeo:
x_test_sm_boo = sc.fit_transform(x_test_sm_boo)

In [58]:
import xgboost as xgb

boosting = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric='logloss'
)
boosting.fit(x_train_boo, y_train_boo)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=3, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, ...)

In [59]:
boosting_sm = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric='logloss'
)
boosting_sm.fit(x_train_sm_boo, y_train_sm_boo)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=3, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, ...)

In [60]:
y_pred_boo = boosting.predict(x_test_boo)
accuracy_boo = accuracy_score(y_test_boo, y_pred_boo)
print('Accuracy del Modelo de Boosting: %.3f' % accuracy_boo)

Accuracy del Modelo de Boosting: 0.841


In [61]:
y_pred_sm_boo = boosting_sm.predict(x_test_sm_boo)
accuracy_sm_boo = accuracy_score(y_test_sm_boo, y_pred_sm_boo)
print('Accuracy del Modelo de Boosting con Oversampling: %.3f' % accuracy_sm_boo)

Accuracy del Modelo de Boosting con Oversampling: 0.588


In [62]:
precision_boo = precision_score(y_test_boo, y_pred_boo)
print('Precision del Modelo de Boosting: %.3f' % precision_boo)

Precision del Modelo de Boosting: 0.000


In [63]:
precision_sm_boo = precision_score(y_test_sm_boo, y_pred_sm_boo)
print('Precision del Modelo de Boosting con Oversampling: %.3f' % precision_sm_boo)

Precision del Modelo de Boosting con Oversampling: 0.553


In [64]:
recall_boo = recall_score(y_test_boo, y_pred_boo)
print('Recall del Modelo de Boosting: %.3f' % recall_boo)

Recall del Modelo de Boosting: 0.000


In [65]:
recall_sm_boo = recall_score(y_test_sm_boo, y_pred_sm_boo)
print('Recall del Modelo de Boosting con Oversampling: %.3f' % recall_sm_boo)

Recall del Modelo de Boosting con Oversampling: 0.921


In [66]:
matriz_boo = confusion_matrix(y_test_boo, y_pred_boo)
print('Matriz de Confusión de Boosting:')
print(matriz_boo)

Matriz de Confusión de Boosting:
[[1962    0]
 [ 371    0]]


In [67]:
matriz_sm_boo = confusion_matrix(y_test_sm_boo, y_pred_sm_boo)
print('Matriz de Confusión de Boosting con Oversampling:')
print(matriz_sm_boo)

Matriz de Confusión de Boosting con Oversampling:
[[ 502 1462]
 [ 155 1806]]


In [68]:
print(classification_report(y_test_boo, y_pred_boo))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91      1962
        True       0.00      0.00      0.00       371

    accuracy                           0.84      2333
   macro avg       0.42      0.50      0.46      2333
weighted avg       0.71      0.84      0.77      2333



In [69]:
print(classification_report(y_test_sm_boo, y_pred_sm_boo))

              precision    recall  f1-score   support

       False       0.76      0.26      0.38      1964
        True       0.55      0.92      0.69      1961

    accuracy                           0.59      3925
   macro avg       0.66      0.59      0.54      3925
weighted avg       0.66      0.59      0.54      3925



### Stacking

In [70]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [71]:
x_train_st, x_test_st, y_train_st, y_test_st = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_st = sc.fit_transform(x_train_st)
#Escalo Datos de Testeo:
x_test_st = sc.fit_transform(x_test_st)

In [73]:
x_train_sm_st, x_test_sm_st, y_train_sm_st, y_test_sm_st = train_test_split(x_sm, y_sm,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm_st = sc.fit_transform(x_train_sm_st)
#Escalo Datos de Testeo:
x_test_sm_st = sc.fit_transform(x_test_sm_st)

In [75]:
modelos_stacking = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stacking = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stacking.fit(x_train_st, y_train_st)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [76]:
modelos_stacking_sm = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stacking_sm = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stacking_sm.fit(x_train_sm_st, y_train_sm_st)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [77]:
y_pred_st = stacking.predict(x_test_st)
accuracy_st = accuracy_score(y_test_st, y_pred_st)
print(f'Accuracy del Modelo de Stacking: {accuracy_st:4f}')

Accuracy del Modelo de Stacking: 0.840977


In [78]:
y_pred_sm_st = stacking.predict(x_test_sm_st)
accuracy_sm_st = accuracy_score(y_test_sm_st, y_pred_sm_st)
print(f'Accuracy del Modelo de Stacking con Oversampling: {accuracy_sm_st:4f}')

Accuracy del Modelo de Stacking con Oversampling: 0.502675


In [79]:
precision_st = precision_score(y_test_st, y_pred_st)
print('Precision del Modelo de Stacking: %.3f' % precision_st)

Precision del Modelo de Stacking: 0.000


In [80]:
precision_sm_st = precision_score(y_test_sm_st, y_pred_sm_st)
print('Precision del Modelo de Stacking con Oversampling: %.3f' % precision_sm_st)

Precision del Modelo de Stacking con Oversampling: 0.909


In [81]:
recall_st = recall_score(y_test_st, y_pred_st)
print('Recall del Modelo de Stacking: %.3f' % recall_st)

Recall del Modelo de Stacking: 0.000


In [82]:
recall_sm_st = recall_score(y_test_sm_st, y_pred_sm_st)
print('Recall del Modelo de Stacking con Oversampling: %.3f' % recall_sm_st)

Recall del Modelo de Stacking con Oversampling: 0.005


In [83]:
matriz_st = confusion_matrix(y_test_st, y_pred_st)
print('Matriz de Confusión de Boosting:')
print(matriz_st)

Matriz de Confusión de Boosting:
[[1962    0]
 [ 371    0]]


In [84]:
matriz_sm_st = confusion_matrix(y_test_sm_st, y_pred_sm_st)
print('Matriz de Confusión de Boosting con Oversampling:')
print(matriz_sm_st)

Matriz de Confusión de Boosting con Oversampling:
[[1963    1]
 [1951   10]]


In [85]:
print(classification_report(y_test_st, y_pred_st))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91      1962
        True       0.00      0.00      0.00       371

    accuracy                           0.84      2333
   macro avg       0.42      0.50      0.46      2333
weighted avg       0.71      0.84      0.77      2333



In [86]:
print(classification_report(y_test_sm_st, y_pred_sm_st))

              precision    recall  f1-score   support

       False       0.50      1.00      0.67      1964
        True       0.91      0.01      0.01      1961

    accuracy                           0.50      3925
   macro avg       0.71      0.50      0.34      3925
weighted avg       0.71      0.50      0.34      3925

