<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

<tr>

    <td><img src=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZcU0_2fgIIcOXf6T0U0AQq1Ld4wMw9s1at5scGVpT5VEmPPTq6-CRSGJhQkrSSrSfi7o&usqp=CAU alt="Drawing" style="width: 70px;"/></td>

    <td><td style="font-size:3vw"><font color='OrangeRed'><b>Trabajo Final Master en Big Data</b></font></td>

</tr>

# Trabajo Final - Máster en Big Data - Fernández, García y Payovich

## Modelos de Base: Random Forest, Regresión Logística, Bagging, Boosting y Stacking

### Importación de Librerías

In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # División del dataset
import matplotlib.pyplot as plt # Plotear
from sklearn.linear_model import LinearRegression # Modelo de ML
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, classification_report # Métricas
pd.options.display.max_columns= None
import warnings

In [2]:
warnings.filterwarnings('ignore')

### Importación y Transformación de las Bases

In [3]:
df = pd.read_csv('base_final_EDA.csv', delimiter= ',')

In [4]:
x = df.drop(['detractor'], axis=1)

In [5]:
y = df['detractor']

In [6]:
y.value_counts()

False    9812
True     1850
Name: detractor, dtype: int64

### Random Forest:

In [7]:
x_train_rf, x_test_rf, y_train_rf, y_test_rf = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_rf = sc.fit_transform(x_train_rf)
#Escalo Datos de Testeo:
x_test_rf = sc.fit_transform(x_test_rf)

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf.fit(x_train_rf, y_train_rf)
y_pred_rf = rf.predict(x_test_rf).round()

In [10]:
accuracy_rf = accuracy_score(y_test_rf, y_pred_rf)
print('Accuracy del modelo Random Forest: %.3f' % accuracy_rf)

Accuracy del modelo Random Forest: 0.829


In [11]:
precision_rf = precision_score(y_test_rf, y_pred_rf)
print('Precision del modelo Random Forest: %.3f' % precision_rf)

Precision del modelo Random Forest: 0.000


In [12]:
recall_rf = recall_score(y_test_rf, y_pred_rf)
print('Recall del Modelo Random Forest: %.3f' % recall_rf)

Recall del Modelo Random Forest: 0.000


In [13]:
matriz_rf = confusion_matrix(y_test_rf, y_pred_rf)
print('Matriz de Confusión:')
print(matriz_rf)

Matriz de Confusión:
[[1935    0]
 [ 398    0]]


In [14]:
print(classification_report(y_test_rf, y_pred_rf))

              precision    recall  f1-score   support

       False       0.83      1.00      0.91      1935
        True       0.00      0.00      0.00       398

    accuracy                           0.83      2333
   macro avg       0.41      0.50      0.45      2333
weighted avg       0.69      0.83      0.75      2333



### Random Forest con Oversampling:

In [15]:
x_train_sm, x_test_sm, y_train_sm, y_test_sm = train_test_split(x, y,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [17]:
#OverSampling:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
x_train_sm, y_train_sm = sm.fit_resample(x_train_sm, y_train_sm)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_sm = sc.fit_transform(x_train_sm)
#Escalo Datos de Testeo:
x_test_sm = sc.fit_transform(x_test_sm)

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf_sm = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_sm.fit(x_train_sm, y_train_sm)
y_pred_sm = rf_sm.predict(x_test_sm).round()

In [20]:
accuracy_rf_sm = accuracy_score(y_test_sm, y_pred_sm)
print('Accuracy del Random Forest con Oversampling: %.3f' % accuracy_rf_sm)

Accuracy del Random Forest con Oversampling: 0.349


In [21]:
precision_sm = precision_score(y_test_sm, y_pred_sm)
print('Precision del modelo Random Forest con Oversampling: %.3f' % precision_sm)

Precision del modelo Random Forest con Oversampling: 0.182


In [22]:
recall_sm = recall_score(y_test_sm, y_pred_sm)
print('Recall del Modelo Random Forest con Oversampling: %.3f' % recall_sm)

Recall del Modelo Random Forest con Oversampling: 0.830


In [23]:
matriz_sm = confusion_matrix(y_test_sm, y_pred_sm)
print('Matriz de Confusión:')
print(matriz_sm)

Matriz de Confusión:
[[ 492 1452]
 [  66  323]]


In [24]:
print(classification_report(y_test_sm, y_pred_sm))

              precision    recall  f1-score   support

       False       0.88      0.25      0.39      1944
        True       0.18      0.83      0.30       389

    accuracy                           0.35      2333
   macro avg       0.53      0.54      0.35      2333
weighted avg       0.77      0.35      0.38      2333



### Random Forest con Undersampling

In [25]:
x_train_us, x_test_us, y_train_us, y_test_us = train_test_split(x, y,
                                   random_state=104, 
                                   test_size=0.20, 
                                   shuffle=True)

In [26]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state = 42)
x_train_us, y_train_us = rus.fit_resample(x_train_us, y_train_us)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_us = sc.fit_transform(x_train_us)
#Escalo Datos de Testeo:
x_test_us = sc.fit_transform(x_test_us)

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf_us = RandomForestClassifier(random_state = 50, n_estimators = 500)
rf_us.fit(x_train_us, y_train_us)
y_pred_us = rf_us.predict(x_test_us).round()

In [29]:
accuracy_us = accuracy_score(y_test_us, y_pred_us)
print('Accuracy del Random Forest con Undersampling: %.3f' % accuracy_us)

Accuracy del Random Forest con Undersampling: 0.615


In [30]:
precision_us = precision_score(y_test_us, y_pred_us)
print('Precision del modelo Random Forest con Undersampling %.3f' % precision_us)

Precision del modelo Random Forest con Undersampling 0.222


In [31]:
recall_us = recall_score(y_test_us, y_pred_us)
print('Recall del Modelo Random Forest con Undersampling: %.3f' % recall_us)

Recall del Modelo Random Forest con Undersampling: 0.522


In [32]:
matriz_us = confusion_matrix(y_test_us, y_pred_us)
print('Matriz de Confusión:')
print(matriz_us)

Matriz de Confusión:
[[1232  712]
 [ 186  203]]


In [33]:
print(classification_report(y_test_us, y_pred_us))

              precision    recall  f1-score   support

       False       0.87      0.63      0.73      1944
        True       0.22      0.52      0.31       389

    accuracy                           0.62      2333
   macro avg       0.55      0.58      0.52      2333
weighted avg       0.76      0.62      0.66      2333



### Random Forest con Balanceo

In [34]:
x_train_rfb, x_test_rfb, y_train_rfb, y_test_rfb = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [35]:
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_rfb = sc.fit_transform(x_train_rfb)
#Escalo Datos de Testeo:
x_test_rfb = sc.fit_transform(x_test_rfb)

In [36]:
rfb = RandomForestClassifier(random_state = 50, n_estimators = 500, class_weight='balanced')
rfb.fit(x_train_rfb, y_train_rfb)
y_pred_rfb = rfb.predict(x_test_rfb).round()

In [37]:
accuracy_rfb = accuracy_score(y_test_rfb, y_pred_rfb)
print('Accuracy del Random Forest con Balanceo: %.3f' % accuracy_rfb)

Accuracy del Random Forest con Balanceo: 0.829


In [38]:
precision_rfb = precision_score(y_test_rfb, y_pred_rfb)
print('Precision del modelo Random Forest con Balanceo %.3f' % precision_rfb)

Precision del modelo Random Forest con Balanceo 0.000


In [39]:
recall_rfb = recall_score(y_test_rfb, y_pred_rfb)
print('Recall del Modelo Random Forest con Balanceo: %.3f' % recall_rfb)

Recall del Modelo Random Forest con Balanceo: 0.000


### Regresión Logística

In [40]:
x_train_rl, x_test_rl, y_train_rl, y_test_rl = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [41]:
x_train_rlus, x_test_rlus, y_train_rlus, y_test_rlus = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [42]:
x_train_rlsm, x_test_rlsm, y_train_rlsm, y_test_rlsm = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_rl = sc.fit_transform(x_train_rl)
#Escalo Datos de Testeo:
x_test_rl = sc.fit_transform(x_test_rl)

In [44]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state = 42)
x_train_rlus, y_train_rlus = rus.fit_resample(x_train_rlus, y_train_rlus)

In [45]:
#OverSampling:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
x_train_rlsm, y_train_rlsm = sm.fit_resample(x_train_rlsm, y_train_rlsm)

In [46]:
#Escalo Datos de Entrenamiento:
x_train_rlus = sc.fit_transform(x_train_rlus)
#Escalo Datos de Testeo:
x_test_rlus = sc.fit_transform(x_test_rlus)
#Escalo Datos de Entrenamiento:
x_train_rlsm = sc.fit_transform(x_train_rlsm)
#Escalo Datos de Testeo:
x_test_rlsm = sc.fit_transform(x_test_rlsm)

In [48]:
from sklearn.linear_model import LogisticRegression
rl = LogisticRegression(max_iter=1000)
rl.fit(x_train_rl, y_train_rl)
y_pred_rl = rl.predict(x_test_rl)

In [49]:
from sklearn.linear_model import LogisticRegression
rlus = LogisticRegression(max_iter=1000)
rlus.fit(x_train_rlus, y_train_rlus)
y_pred_rlus = rlus.predict(x_test_rlus)

In [50]:
rlsm = LogisticRegression(max_iter=1000)
rlsm.fit(x_train_rlsm, y_train_rlsm)
y_pred_rlsm = rlsm.predict(x_test_rlsm)

In [51]:
accuracy_rl = accuracy_score(y_test_rl, y_pred_rl)
print('Accuracy del Modelo de Regresión Logística: %.3f' % accuracy_rl)

Accuracy del Modelo de Regresión Logística: 0.829


In [52]:
accuracy_rlus = accuracy_score(y_test_rlus, y_pred_rlus)
print('Accuracy del Modelo de Regresión Logística con Undersampling: %.3f' % accuracy_rlus)

Accuracy del Modelo de Regresión Logística con Undersampling: 0.512


In [53]:
accuracy_rlsm = accuracy_score(y_test_rlsm, y_pred_rlsm)
print('Accuracy del Modelo de Regresión Logística con Oversampling: %.3f' % accuracy_rlsm)

Accuracy del Modelo de Regresión Logística con Oversampling: 0.185


In [54]:
precision_rl = precision_score(y_test_rl, y_pred_rl)
print('Precision del Modelo de Regresión Logística %.3f' % precision_rl)

Precision del Modelo de Regresión Logística 0.000


In [55]:
precision_rlus = precision_score(y_test_rlus, y_pred_rlus)
print('Precision del Modelo de Regresión Logística con Undersampling %.3f' % precision_rlus)

Precision del Modelo de Regresión Logística con Undersampling 0.205


In [56]:
precision_rlsm = precision_score(y_test_rlsm, y_pred_rlsm)
print('Precision del Modelo de Regresión Logística con Oversampling %.3f' % precision_rlsm)

Precision del Modelo de Regresión Logística con Oversampling 0.173


In [57]:
recall_rl = recall_score(y_test_rl, y_pred_rl)
print('Recall del Modelo de Regresión Logística: %.3f' % recall_rl)

Recall del Modelo de Regresión Logística: 0.000


In [58]:
recall_rlus = recall_score(y_test_rlus, y_pred_rlus)
print('Recall del Modelo de Regresión Logística con Undersampling: %.3f' % recall_rlus)

Recall del Modelo de Regresión Logística con Undersampling: 0.648


In [59]:
recall_rlsm = recall_score(y_test_rlsm, y_pred_rlsm)
print('Recall del Modelo de Regresión Logística con Oversampling: %.3f' % recall_rlsm)

Recall del Modelo de Regresión Logística con Oversampling: 0.995


### Bagging

In [60]:
x_train_bg, x_test_bg, y_train_bg, y_test_bg = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [61]:
x_train_bgus, x_test_bgus, y_train_bgus, y_test_bgus = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [62]:
x_train_bgsm, x_test_bgsm, y_train_bgsm, y_test_bgsm = train_test_split(x, y,
                                   random_state=130, 
                                   test_size=0.20, 
                                   shuffle=True)

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_bg = sc.fit_transform(x_train_bg)
#Escalo Datos de Testeo:
x_test_bg = sc.fit_transform(x_test_bg)

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_bgus = sc.fit_transform(x_train_bgus)
#Escalo Datos de Testeo:
x_test_bgus = sc.fit_transform(x_test_bgus)

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_bgsm = sc.fit_transform(x_train_bgsm)
#Escalo Datos de Testeo:
x_test_bgsm = sc.fit_transform(x_test_bgsm)

In [66]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state = 42)
x_train_bgus, y_train_bgus = rus.fit_resample(x_train_bgus, y_train_bgus)

In [67]:
#OverSampling:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
x_train_bgsm, y_train_bgsm = sm.fit_resample(x_train_bgsm, y_train_bgsm)

In [68]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

bagging.fit(x_train_bg, y_train_bg)
y_pred_bg = bagging.predict(x_test_bg)

In [69]:
from sklearn.ensemble import BaggingClassifier
baggingus = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

baggingus.fit(x_train_bgus, y_train_bgus)
y_pred_bgus = baggingus.predict(x_test_bg)

In [70]:
from sklearn.ensemble import BaggingClassifier
baggingsm = BaggingClassifier(n_estimators = 10,
                            random_state = 55, n_jobs = -1)

baggingsm.fit(x_train_bgsm, y_train_bgsm)
y_pred_bgsm = baggingsm.predict(x_test_bg)

In [71]:
accuracy_bg = accuracy_score(y_test_bg, y_pred_bg)
print('Accuracy del Modelo de Bagging: %.3f' % accuracy_bg)

Accuracy del Modelo de Bagging: 0.814


In [72]:
accuracy_bgus = accuracy_score(y_test_bgus, y_pred_bgus)
print('Accuracy del Modelo de Bagging con Undersampling: %.3f' % accuracy_bgus)

Accuracy del Modelo de Bagging con Undersampling: 0.659


In [73]:
accuracy_bgsm = accuracy_score(y_test_bgsm, y_pred_bgsm)
print('Accuracy del Modelo de Bagging con Oversampling: %.3f' % accuracy_bgsm)

Accuracy del Modelo de Bagging con Oversampling: 0.212


In [74]:
precision_bg = precision_score(y_test_bg, y_pred_bg)
print('Precision del Modelo de Bagging: %.3f' % precision_bg)

Precision del Modelo de Bagging: 0.235


In [75]:
precision_bgus = precision_score(y_test_bgus, y_pred_bgus)
print('Precision del Modelo de Bagging con Undersampling: %.3f' % precision_bgus)

Precision del Modelo de Bagging con Undersampling: 0.202


In [76]:
precision_bgsm = precision_score(y_test_bgsm, y_pred_bgsm)
print('Precision del Modelo de Bagging con Oversampling: %.3f' % precision_bgsm)

Precision del Modelo de Bagging con Oversampling: 0.171


In [77]:
recall_bg = recall_score(y_test_bg, y_pred_bg)
print('Recall del Modelo de Bagging: %.3f' % recall_bg)

Recall del Modelo de Bagging: 0.040


In [78]:
recall_bgus = recall_score(y_test_bgus, y_pred_bgus)
print('Recall del Modelo de Bagging con Undersampling: %.3f' % recall_bgus)

Recall del Modelo de Bagging con Undersampling: 0.337


In [79]:
recall_bgsm = recall_score(y_test_bgsm, y_pred_bgsm)
print('Recall del Modelo de Bagging con Oversampling: %.3f' % recall_bgsm)

Recall del Modelo de Bagging con Oversampling: 0.940


In [80]:
matriz_bg = confusion_matrix(y_test_bg, y_pred_bg)
print('Matriz de Confusión Bagging:')
print(matriz_bg)

Matriz de Confusión Bagging:
[[1883   52]
 [ 382   16]]


In [81]:
print(classification_report(y_test_bg, y_pred_bg))

              precision    recall  f1-score   support

       False       0.83      0.97      0.90      1935
        True       0.24      0.04      0.07       398

    accuracy                           0.81      2333
   macro avg       0.53      0.51      0.48      2333
weighted avg       0.73      0.81      0.76      2333



### Boosting

In [82]:
x_train_boo, x_test_boo, y_train_boo, y_test_boo = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [83]:
x_train_boo1, x_test_boo1, y_train_boo1, y_test_boo1 = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [84]:
from xgboost import XGBClassifier

In [85]:
boosting = XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric='logloss'
)

boosting.fit(x_train_boo, y_train_boo)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=3, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, ...)

In [86]:
boosting1 = XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric='logloss',
    scale_pos_weight=9
)

boosting1.fit(x_train_boo1, y_train_boo1)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=3, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, ...)

In [87]:
y_pred_boo = boosting.predict(x_test_boo)
accuracy_boo = accuracy_score(y_test_boo, y_pred_boo)
print('Accuracy del Modelo de Boosting: %.3f' % accuracy_boo)

Accuracy del Modelo de Boosting: 0.841


In [88]:
y_pred_boo1 = boosting1.predict(x_test_boo1)
accuracy_boo1 = accuracy_score(y_test_boo1, y_pred_boo1)
print('Accuracy del Modelo de Boosting Sampleado: %.3f' % accuracy_boo1)

Accuracy del Modelo de Boosting Sampleado: 0.365


In [89]:
precision_boo = precision_score(y_test_boo, y_pred_boo)
print('Precision del Modelo de Boosting: %.3f' % precision_boo)

Precision del Modelo de Boosting: 0.500


In [90]:
precision_boo1 = precision_score(y_test_boo1, y_pred_boo1)
print('Precision del Modelo de Boosting Sampleado: %.3f' % precision_boo1)

Precision del Modelo de Boosting Sampleado: 0.185


In [91]:
recall_boo = recall_score(y_test_boo, y_pred_boo)
print('Recall del Modelo de Boosting: %.3f' % recall_boo)

Recall del Modelo de Boosting: 0.003


In [92]:
recall_boo1 = recall_score(y_test_boo1, y_pred_boo1)
print('Recall del Modelo de Boosting Samp: %.3f' % recall_boo1)

Recall del Modelo de Boosting Samp: 0.876


In [93]:
matriz_boo = confusion_matrix(y_test_boo, y_pred_boo)
print('Matriz de Confusión de Boosting:')
print(matriz_boo)

Matriz de Confusión de Boosting:
[[1961    1]
 [ 370    1]]


In [94]:
print(classification_report(y_test_boo, y_pred_boo))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91      1962
        True       0.50      0.00      0.01       371

    accuracy                           0.84      2333
   macro avg       0.67      0.50      0.46      2333
weighted avg       0.79      0.84      0.77      2333



### Stacking

In [95]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [96]:
x_train_st, x_test_st, y_train_st, y_test_st = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [97]:
x_train_stsm, x_test_stsm, y_train_stsm, y_test_stsm = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [98]:
x_train_stus, x_test_stus, y_train_stus, y_test_stus = train_test_split(x, y,
                                   random_state=42, 
                                   test_size=0.20, 
                                   shuffle=True)

In [99]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Escalo Datos de Entrenamiento:
x_train_st = sc.fit_transform(x_train_st)
#Escalo Datos de Testeo:
x_test_st = sc.fit_transform(x_test_st)
#Escalo Datos de Entrenamiento:
x_train_stsm = sc.fit_transform(x_train_stsm)
#Escalo Datos de Testeo:
x_test_stsm = sc.fit_transform(x_test_stsm)
#Escalo Datos de Entrenamiento:
x_train_stus = sc.fit_transform(x_train_stus)
#Escalo Datos de Testeo:
x_test_stus = sc.fit_transform(x_test_stus)

In [100]:
modelos_stacking = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stacking = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stacking.fit(x_train_st, y_train_st)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [101]:
modelos_stackingsm = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stackingsm = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stackingsm.fit(x_train_stsm, y_train_stsm)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [102]:
modelos_stackingus = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', BaggingClassifier(n_estimators=100, random_state=42)),
]

meta_modelo = LogisticRegression()

stackingus = StackingClassifier(estimators=modelos_stacking, final_estimator=meta_modelo)

stackingus.fit(x_train_stus, y_train_stus)

StackingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                               ('gb',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=LogisticRegression())

In [103]:
y_pred_st = stacking.predict(x_test_st)
accuracy_st = accuracy_score(y_test_st, y_pred_st)
print(f'Accuracy del Modelo de Stacking: {accuracy_st:4f}')

Accuracy del Modelo de Stacking: 0.840977


In [104]:
y_pred_stsm = stacking.predict(x_test_stsm)
accuracy_stsm = accuracy_score(y_test_stsm, y_pred_stsm)
print(f'Accuracy del Modelo de Stacking con Oversampling: {accuracy_stsm:4f}')

Accuracy del Modelo de Stacking con Oversampling: 0.840977


In [105]:
y_pred_stus = stacking.predict(x_test_stus)
accuracy_stus = accuracy_score(y_test_stus, y_pred_stus)
print(f'Accuracy del Modelo de Stacking con Oversampling: {accuracy_stus:4f}')

Accuracy del Modelo de Stacking con Oversampling: 0.840977


In [106]:
precision_st = precision_score(y_test_st, y_pred_st)
print('Precision del Modelo de Stacking: %.3f' % precision_st)

Precision del Modelo de Stacking: 0.000


In [107]:
precision_stsm = precision_score(y_test_stsm, y_pred_stsm)
print('Precision del Modelo de Stacking con Oversampling: %.3f' % precision_stsm)

Precision del Modelo de Stacking con Oversampling: 0.000


In [108]:
precision_stus = precision_score(y_test_stus, y_pred_stus)
print('Precision del Modelo de Stacking con Undersampling: %.3f' % precision_stus)

Precision del Modelo de Stacking con Undersampling: 0.000


In [109]:
recall_st = recall_score(y_test_st, y_pred_st)
print('Recall del Modelo de Stacking: %.3f' % recall_st)

Recall del Modelo de Stacking: 0.000


In [110]:
recall_stsm = recall_score(y_test_stsm, y_pred_stsm)
print('Recall del Modelo de Stacking con Undersampling: %.3f' % recall_stsm)

Recall del Modelo de Stacking con Undersampling: 0.000


In [111]:
recall_stus = recall_score(y_test_stus, y_pred_stus)
print('Recall del Modelo de Stacking con Undersampling: %.3f' % recall_stus)

Recall del Modelo de Stacking con Undersampling: 0.000


In [112]:
matriz_st = confusion_matrix(y_test_st, y_pred_st)
print('Matriz de Confusión de Boosting:')
print(matriz_st)

Matriz de Confusión de Boosting:
[[1962    0]
 [ 371    0]]
